###
POST http://localhost:5141/api/allergens/add-many
Content-Type: application/json

[
    {
        "Name" : "Lepek"
    },
    {
        "Name" : "Laktóza"
    },
    {
        "Name" : "Ořechy"
    },
    {
        "Name" : "Vejce"
    },
    {
        "Name" : "Ryby"
    },
    {
        "Name" : "Maso"
    }
]

###
POST http://localhost:5141/api/allergens/add
Content-Type: application/json

{
    "Name" : "Maso"
}

### test if cascading enabled on foreign keys
DELETE http://localhost:5141/api/allergens/delete/6

###
GET http://localhost:5141/api/allergens/all

###
DELETE http://localhost:5141/api/allergens/delete-all