POST http://localhost:5141/api/allergens/add-many
Content-Type: application/json

[
    {
        "Name" : "Lepek"
    },
    {
        "Name" : "Laktóza"
    },
    {
        "Name" : "Ořechy"
    },
    {
        "Name" : "Vejce"
    },
    {
        "Name" : "Ryby"
    },
    {
        "Name" : "Maso"
    }
]