###
POST http://localhost:5141/api/meals/add-many
Content-Type: application/json

[
    {
        "name" : "Caesar salát",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-01",
        "allergens" : 
        [
            {
                "name": "Maso"
            },
            {
                "name": "Laktóza"
            },
            {
                "name": "Lepek"
            }
        ]
    },
    {
        "name" : "Filet z lososa",
        "mealTime" : "Lunch",
        "type" : "Main",
        "date" : "2024-09-01",
        "allergens" : 
        [
            {
                "name": "Maso"
            },
            {
                "name": "Ryby"
            },
            {
                "name": "Lepek"
            }
        ]
    },
    {
        "name" : "Palak paneer",
        "mealTime" : "Lunch",
        "type" : "Main",
        "date" : "2024-09-01",
        "allergens" : 
        [
            {
                "name": "Maso"
            },
            {
                "name": "Ryby"
            },
            {
                "name": "Lepek"
            }
        ]
    },
    {
        "name" : "Brokolicová polévka",
        "mealTime" : "Lunch",
        "type" : "Soup",
        "date" : "2024-09-01",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Laktóza"
            }
        ]
    },
    {
        "name" : "Houbová polévka",
        "mealTime" : "Lunch",
        "type" : "Soup",
        "date" : "2024-09-01",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Laktóza"
            }
        ]
    },
    {
        "name" : "Grilovaná kuřecí prsa",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-02",
        "allergens" : 
        [
            {
                "name": "Maso"
            }
        ]
    },
    {
        "name" : "Minestrone polévka",
        "mealTime" : "Lunch",
        "type" : "Soup",
        "date" : "2024-09-02",
        "allergens" : 
        [
            {
                "name": "Lepek"
            }
        ]
    },
    {
        "name" : "Špagety Bolognese",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-03",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Maso"
            }
        ]
    },
    {
        "name" : "Zeleninové Stir Fry",
        "mealTime" : "Lunch",
        "type" : "Main",
        "date" : "2024-09-03",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Ořechy"
            }
        ]
    },
    {
        "name" : "Hovězí guláš",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-04",
        "allergens" : 
        [
            {
                "name": "Maso"
            }
        ]
    },
    {
        "name" : "Krémová rajčatová polévka",
        "mealTime" : "Lunch",
        "type" : "Soup",
        "date" : "2024-09-04",
        "allergens" : 
        [
            {
                "name": "Laktóza"
            },
            {
                "name": "Lepek"
            }
        ]
    },
    {
        "name" : "Tofu salát",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-05",
        "allergens" : 
        [
            {
                "name": "Ořechy"
            }
        ]
    },
    {
        "name" : "Kuřecí nudlová polévka",
        "mealTime" : "Lunch",
        "type" : "Soup",
        "date" : "2024-09-05",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Maso"
            },
            {
                "name": "Vejce"
            }
        ]
    },
    {
        "name" : "Ryba s hranolky",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-06",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Ryby"
            }
        ]
    },
    {
        "name" : "Dýňová polévka",
        "mealTime" : "Lunch",
        "type" : "Soup",
        "date" : "2024-09-06",
        "allergens" : 
        [
            {
                "name": "Laktóza"
            }
        ]
    },
    {
        "name" : "Jehněčí kari",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-07",
        "allergens" : 
        [
            {
                "name": "Maso"
            }
        ]
    },
    {
        "name" : "Caesar salát",
        "mealTime" : "Lunch",
        "type" : "Main",
        "date" : "2024-09-07",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Vejce"
            },
            {
                "name": "Laktóza"
            }
        ]
    },
    {
        "name" : "Hovězí Stroganoff",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-08",
        "allergens" : 
        [
            {
                "name": "Maso"
            },
            {
                "name": "Laktóza"
            },
            {
                "name": "Lepek"
            }
        ]
    },
    {
        "name" : "Miso polévka",
        "mealTime" : "Lunch",
        "type" : "Soup",
        "date" : "2024-09-08",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Ryby"
            }
        ]
    },
    {
        "name" : "Rizoto s krevetami",
        "mealTime" : "Dinner",
        "type" : "Main",
        "date" : "2024-09-09",
        "allergens" : 
        [
            {
                "name": "Lepek"
            },
            {
                "name": "Ryby"
            }
        ]
    }
]
