POST http://localhost:5141/api/orders/add-many
Content-Type: application/json

[
    { "participantId": 0, "mealId": 0 },
    { "participantId": 1, "mealId": 0 },
    { "participantId": 0, "mealId": 1 },
    { "participantId": 0, "mealId": 2 },
    { "participantId": 2, "mealId": 3 },
    { "participantId": 3, "mealId": 4 },
    { "participantId": 4, "mealId": 5 },
    { "participantId": 5, "mealId": 6 },
    { "participantId": 6, "mealId": 7 },
    { "participantId": 7, "mealId": 8 },
    { "participantId": 7, "mealId": 0 },
    { "participantId": 8, "mealId": 9 },
    { "participantId": 9, "mealId": 10 },
    { "participantId": 9, "mealId": 13 },
    { "participantId": 10, "mealId": 11 },
    { "participantId": 11, "mealId": 12 },
    { "participantId": 11, "mealId": 17 },
    { "participantId": 12, "mealId": 13 },
    { "participantId": 12, "mealId": 16 },
    { "participantId": 13, "mealId": 14 },
    { "participantId": 14, "mealId": 15 },
    { "participantId": 14, "mealId": 16 },
    { "participantId": 14, "mealId": 9 },
    { "participantId": 14, "mealId": 17 },
    { "participantId": 0, "mealId": 8 },
    { "participantId": 0, "mealId": 10 },
    { "participantId": 8, "mealId": 16 },
    { "participantId": 8, "mealId": 15 },
    { "participantId": 2, "mealId": 7 },
    { "participantId": 3, "mealId": 1 },
    { "participantId": 14, "mealId": 2 }
]
