POST http://localhost:5141/api/participants/add-many
Content-Type: application/json

[
  {
    "firstName": "Alena",
    "lastName": "Nováková",
    "age": 7,
    "phoneNumber": "777251356",
    "birthNumber": "1754079503",
    "diets": [
      {
        "name": "Lepek"
      },
      {
        "name": "Laktóza"
      },
      {
        "name": "Maso"
      }
    ]
  },
  {
    "firstName": "Petr",
    "lastName": "Novák",
    "age": 12,
    "phoneNumber": "608542356",
    "birthNumber": "1203054886",
    "diets": [
      {
        "name": "Ořechy"
      }
    ]
  },
  {
    "firstName": "Karel",
    "lastName": "Černý",
    "age": 7,
    "phoneNumber": "605453482",
    "birthNumber": "1610291551",
    "diets": [
      {
        "name": "Vejce"
      },
      {
        "name": "Ryby"
      }
    ]
  },
  {
    "firstName": "David",
    "lastName": "Dvořák",
    "age": 11,
    "phoneNumber": "712456789",
    "birthNumber": "1306147469",
    "diets": [
      {
        "name": "Lepek"
      }
    ]
  },
  {
    "firstName": "Eva",
    "lastName": "Svobodová",
    "age": 17,
    "phoneNumber": "619845267",
    "birthNumber": "0754188886",
    "diets": [
      {
        "name": "Laktóza"
      }
    ]
  },
  {
    "firstName": "František",
    "lastName": "Veselý",
    "age": 6,
    "phoneNumber": "724582341",
    "birthNumber": "1802153540",
    "diets": [
      {
        "name": "Maso"
      }
    ]
  },
  {
    "firstName": "Lucie",
    "lastName": "Kučerová",
    "age": 5,
    "phoneNumber": "608123456",
    "birthNumber": "1953312493",
    "diets": [
      {
        "name": "Ořechy"
      }
    ]
  },
  {
    "firstName": "Jan",
    "lastName": "Král",
    "age": 1,
    "phoneNumber": "715643278",
    "birthNumber": "2303126694",
    "diets": [
      {
        "name": "Ryby"
      }
    ]
  },
  {
    "firstName": "Iveta",
    "lastName": "Kovářová",
    "age": 11,
    "phoneNumber": "703945612",
    "birthNumber": "1352201026",
    "diets": [
      {
        "name": "Lepek"
      }
    ]
  },
  {
    "firstName": "Jakub",
    "lastName": "Procházka",
    "age": 5,
    "phoneNumber": "710256934",
    "birthNumber": "1812137503",
    "diets": [
      {
        "name": "Vejce"
      }
    ]
  },
  {
    "firstName": "Klára",
    "lastName": "Horáková",
    "age": 10,
    "phoneNumber": "709865432",
    "birthNumber": "1452091366",
    "diets": [
      {
        "name": "Laktóza"
      }
    ]
  },
  {
    "firstName": "Leoš",
    "lastName": "Bartoš",
    "age": 16,
    "phoneNumber": "714582390",
    "birthNumber": "0806178065",
    "diets": [
      {
        "name": "Ořechy"
      }
    ]
  },
  {
    "firstName": "Michaela",
    "lastName": "Štěpánová",
    "age": 6,
    "phoneNumber": "703456789",
    "birthNumber": "1851135352",
    "diets": [
      {
        "name": "Ryby"
      }
    ]
  },
  {
    "firstName": "Nina",
    "lastName": "Jelínková",
    "age": 13,
    "phoneNumber": "719856341",
    "birthNumber": "1156063315",
    "diets": [
      {
        "name": "Maso"
      }
    ]
  },
  {
    "firstName": "Ondřej",
    "lastName": "Malý",
    "age": 8,
    "phoneNumber": "723456789",
    "birthNumber": "1604263705",
    "diets": [
      {
        "name": "Lepek"
      }
    ]
  }
]
